Data Preprocessing on Breast Cancer Dataset - 10/18/2026 - addsmi1720

In [1]:
# Import necessary libraries
import pandas as pd
from datetime import datetime
from IPython.display import display, Markdown
import warnings
warnings.filterwarnings("ignore")

todays_date = datetime.now().strftime("%Y-%m-%d")
student_id = "addsmi1720"

# Load the Breast Cancer dataset into a pandas DataFrame
data = pd.read_csv('breastCancerDataset.csv')

display(Markdown("### Load and Explore the Dataset"))
display(Markdown(f"Date: {todays_date}"))
display(Markdown(f"Student ID: {student_id}"))

# Get a concise summary of the DataFrame
print(data.info())

# Get descriptive statistics for the dataset
display(data.describe())

### Load and Explore the Dataset

Date: 2026-10-18

Student ID: addsmi1720

<class 'pandas.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  569 non-null    int64
 1   Diagnosis           569 non-null    str
 2   radius1             569 non-null    float64
 3   texture1            569 non-null    float64
 4   perimeter1          569 non-null    float64
 5   area1               569 non-null    float64
 6   smoothness1         569 non-null    float64
 7   compactness1        569 non-null    float64
 8   concavity1          569 non-null    float64
 9   concave_points1     569 non-null    float64
 10  symmetry1           569 non-null    float64
 11  fractal_dimension1  569 non-null    float64
 12  radius2             569 non-null    float64
 13  texture2            569 non-null    float64
 14  perimeter2          569 non-null    float64
 15  area2               569 non-null    float64
 16  smoothness2         569 non-null    float64
 17  compactness2        569 non-null    float64
 18  concavity2          569 non-null    float64
 19  concave_points2     569 non-null    float64
 20  symmetry2           569 non-null    float64
 21  fractal_dimension2  569 non-null    float64
 22  radius3             569 non-null    float64
 23  texture3            569 non-null    float64
 24  perimeter3          569 non-null    float64
 25  area3               569 non-null    float64
 26  smoothness3         569 non-null    float64
 27  compactness3        569 non-null    float64
 28  concavity3          569 non-null    float64
 29  concave_points3     569 non-null    float64
 30  symmetry3           569 non-null    float64
 31  fractal_dimension3  569 non-null    float64
dtypes: float64(30), int64(1), str(1)
memory usage: 142.4 KB
None

,ID,radius1,texture1,perimeter1,area1,smoothness1,compactness1,concavity1,concave_points1,symmetry1,...,radius3,texture3,perimeter3,area3,smoothness3,compactness3,concavity3,concave_points3,symmetry3,fractal_dimension3
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,284.000000,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,...,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946
std,164.400426,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,...,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061
min,0.000000,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,142.000000,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,...,13.010000,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460
50%,284.000000,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,...,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040
75%,426.000000,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,...,18.790000,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080
max,568.000000,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

In [2]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

display(Markdown("### Preprocess the Data"))
display(Markdown(f"Date: {todays_date}"))
display(Markdown(f"Student ID: {student_id}"))

# Correct any missing values by filling numerical columns with the median
missing_values = data.isnull().sum()
print(f"Missing values before cleaning: {missing_values.sum()}")
for column in data.select_dtypes(include=['number']).columns:
    data[column] = data[column].fillna(data[column].median())
print(f"Missing values after cleaning: {data.isnull().sum().sum()}")

# Identify and remove any duplicate rows
duplicates = data.duplicated().sum()
print(f"Duplicate rows found: {duplicates}")
data = data.drop_duplicates()
print(f"Rows after removing duplicates: {data.shape[0]}")

# Encode the target: Malignant (M) = 1, Benign (B) = 0
data['Diagnosis'] = data['Diagnosis'].map({'M': 1, 'B': 0})

# Standardize the concavity1 and concavity3 features
scaler = StandardScaler()
data[['concavity1', 'concavity3']] = scaler.fit_transform(data[['concavity1', 'concavity3']])
display(data[['concavity1', 'concavity3']].describe().loc[['mean', 'std']].round(3))

# Features and target (ID is a record identifier, not a measurement, so it is excluded)
X = data.drop(columns=['ID', 'Diagnosis'])
y = data['Diagnosis']

# Split the data into training (70%) and testing (30%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
print(f"Training set size: {X_train.shape[0]} samples")
print(f"Test set size: {X_test.shape[0]} samples")

### Preprocess the Data

Date: 2026-10-18

Student ID: addsmi1720

Missing values before cleaning: 0
Missing values after cleaning: 0
Duplicate rows found: 0
Rows after removing duplicates: 569

      concavity1  concavity3
mean       0.000       0.000
std        1.001       1.001

Training set size: 398 samples
Test set size: 171 samples

In [3]:
from sklearn.svm import SVC

# Fit the SVM model to the training data
svm_model = SVC(random_state=42)
svm_model.fit(X_train, y_train)

# Predict the target values for the test data
y_pred_svm = svm_model.predict(X_test)

print("SVM model training completed.")

SVM model training completed.

In [4]:
from sklearn.metrics import accuracy_score, classification_report

display(Markdown("### Evaluate the SVM Model"))
display(Markdown(f"Date: {todays_date}"))
display(Markdown(f"Student ID: {student_id}"))

print(f"Accuracy Score: {accuracy_score(y_test, y_pred_svm):.4f}")
print("Classification Report:")
print(classification_report(y_test, y_pred_svm, target_names=['Benign', 'Malignant']))

### Evaluate the SVM Model

Date: 2026-10-18

Student ID: addsmi1720

Accuracy Score: 0.9357
Classification Report:
              precision    recall  f1-score   support

      Benign       0.91      1.00      0.95       108
   Malignant       1.00      0.83      0.90        63

    accuracy                           0.94       171
   macro avg       0.95      0.91      0.93       171
weighted avg       0.94      0.94      0.93       171

In [5]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid for SVM tuning
svm_param_grid = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf', 'poly']
}

# Use GridSearchCV to find the best hyperparameters
svm_grid = GridSearchCV(SVC(random_state=42), svm_param_grid, cv=5, scoring='accuracy')
svm_grid.fit(X_train, y_train)

# Refit the model using the best parameters
tuned_svm = SVC(**svm_grid.best_params_, random_state=42)
tuned_svm.fit(X_train, y_train)
y_pred_tuned_svm = tuned_svm.predict(X_test)

print("SVM grid search completed.")

SVM grid search completed.

In [6]:
display(Markdown("### Evaluate the Tuned SVM Model"))
display(Markdown(f"Date: {todays_date}"))
display(Markdown(f"Student ID: {student_id}"))

print(f"Best Parameters: {svm_grid.best_params_}")
print(f"Best Cross-Validation Score: {svm_grid.best_score_:.4f}")
print(f"Accuracy Score: {accuracy_score(y_test, y_pred_tuned_svm):.4f}")
print("Classification Report:")
print(classification_report(y_test, y_pred_tuned_svm, target_names=['Benign', 'Malignant']))

### Evaluate the Tuned SVM Model

Date: 2026-10-18

Student ID: addsmi1720

Best Parameters: {'C': 10, 'kernel': 'linear'}
Best Cross-Validation Score: 0.9623
Accuracy Score: 0.9708
Classification Report:
              precision    recall  f1-score   support

      Benign       0.98      0.97      0.98       108
   Malignant       0.95      0.97      0.96        63

    accuracy                           0.97       171
   macro avg       0.97      0.97      0.97       171
weighted avg       0.97      0.97      0.97       171

In [7]:
from xgboost import XGBClassifier

# Fit the XGBoost model to the training data
xgb_model = XGBClassifier(random_state=42, eval_metric='logloss')
xgb_model.fit(X_train, y_train)

# Predict the target values for the test data
y_pred_xgb = xgb_model.predict(X_test)

print("XGBoost model training completed.")

XGBoost model training completed.

In [8]:
display(Markdown("### Evaluate the XGBoost Model"))
display(Markdown(f"Date: {todays_date}"))
display(Markdown(f"Student ID: {student_id}"))

print(f"Accuracy Score: {accuracy_score(y_test, y_pred_xgb):.4f}")
print("Classification Report:")
print(classification_report(y_test, y_pred_xgb, target_names=['Benign', 'Malignant']))

### Evaluate the XGBoost Model

Date: 2026-10-18

Student ID: addsmi1720

Accuracy Score: 0.9708
Classification Report:
              precision    recall  f1-score   support

      Benign       0.98      0.97      0.98       108
   Malignant       0.95      0.97      0.96        63

    accuracy                           0.97       171
   macro avg       0.97      0.97      0.97       171
weighted avg       0.97      0.97      0.97       171

In [9]:
# Define the parameter grid for XGBoost tuning
xgb_param_grid = {
    'n_estimators': [50, 100],
    'learning_rate': [0.1, 0.2],
    'max_depth': [3, 4]
}

# Use GridSearchCV to find the best hyperparameters
xgb_grid = GridSearchCV(XGBClassifier(random_state=42, eval_metric='logloss'), xgb_param_grid, cv=5, scoring='accuracy')
xgb_grid.fit(X_train, y_train)

# Refit the model using the best parameters
tuned_xgb = XGBClassifier(**xgb_grid.best_params_, random_state=42, eval_metric='logloss')
tuned_xgb.fit(X_train, y_train)
y_pred_tuned_xgb = tuned_xgb.predict(X_test)

print("XGBoost grid search completed.")

XGBoost grid search completed.

In [10]:
display(Markdown("### Evaluate the Tuned XGBoost Model"))
display(Markdown(f"Date: {todays_date}"))
display(Markdown(f"Student ID: {student_id}"))

print(f"Best Parameters: {xgb_grid.best_params_}")
print(f"Best Cross-Validation Score: {xgb_grid.best_score_:.4f}")
print(f"Accuracy Score: {accuracy_score(y_test, y_pred_tuned_xgb):.4f}")
print("Classification Report:")
print(classification_report(y_test, y_pred_tuned_xgb, target_names=['Benign', 'Malignant']))

### Evaluate the Tuned XGBoost Model

Date: 2026-10-18

Student ID: addsmi1720

Best Parameters: {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 100}
Best Cross-Validation Score: 0.9673
Accuracy Score: 0.9591
Classification Report:
              precision    recall  f1-score   support

      Benign       0.96      0.97      0.97       108
   Malignant       0.95      0.94      0.94        63

    accuracy                           0.96       171
   macro avg       0.96      0.95      0.96       171
weighted avg       0.96      0.96      0.96       171

## Analyze and Interpret

**1. In what ways could bias be implemented into this dataset? How can bias be mitigated from similar medical datasets?**

This dataset comes from fine needle aspirate images collected at a single hospital system, so it reflects one patient population, one lab's equipment, and one team's process. The features were measured from cell nuclei that a person selected on the digitized images, so which cells got measured, and how their outlines were traced, depended on human judgment. There are also no age, race, or other demographic fields, so there is no way to check whether the model works equally well for different groups of patients, and patients who were never referred for a biopsy are not in the data at all. The class balance is another built-in choice: 37% of these samples are malignant, which is far higher than in a general screening population, so a model trained here could overcall cancer elsewhere. To reduce bias in similar medical datasets, I would collect data from multiple hospitals and equipment types, record demographic information so performance can be checked for each subgroup, use stratified splits and report recall for the malignant class instead of accuracy alone, since a missed cancer costs far more than a false alarm, and validate the model on an outside dataset before trusting it on new patients.

**2. Compare the performance of the tuned SVM and XGBoost models. Which model performs better and why?**

The tuned SVM performed slightly better on the test set. GridSearchCV picked a linear kernel with C = 10, which reached 97.08% accuracy and a malignant recall of 0.97, missing 2 of the 63 malignant tumors. The tuned XGBoost model (learning rate 0.1, max depth 3, 100 trees) reached 95.91% accuracy and a malignant recall of 0.94, missing 4. The linear kernel won because the features in this dataset, such as radius, perimeter, area, and concavity, separate benign and malignant tumors almost along a straight boundary, so a simple model fits the pattern without overfitting. The RBF and poly kernels scored lower (91% to 92% in cross-validation at best), because only concavity1 and concavity3 were standardized and the unscaled area features dominate their distance calculations, while the linear kernel is less affected by that. The gap between the two tuned models is small, though. XGBoost actually had the higher cross-validation score (96.73% vs 96.23%), and the 1.2 point test difference comes down to 2 patients out of 171, so on a different split the result could flip. Tuning also did not help XGBoost here: the default XGBoost model scored 97.08% on the test set, the same as the tuned SVM, which shows that GridSearchCV chooses settings based on cross-validation and that a small test set can disagree with it.